# Generated by Django 5.2.3 on 2025-06-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=10),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
